# Docker Compose for Coolify deployment
# Following Coolify best practices - no exposed ports by default
version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: biblia-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-bibliasoe}
      POSTGRES_USER: ${DB_USER:-soe}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
      - ./manual_backup.sql:/docker-entrypoint-initdb.d/restore.sql:ro
    networks:
      - biblia-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-soe} -d ${DB_NAME:-bibliasoe}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    labels:
      - "coolify.managed=true"

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: biblia-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-soe}:${DB_PASSWORD}@db:5432/${DB_NAME:-bibliasoe}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-bibliasoe}
      - DB_USER=${DB_USER:-soe}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - biblia-network
    labels:
      - "coolify.managed=true"

  # Nuxt 3 Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
    container_name: biblia-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NITRO_PORT=3000
      - NITRO_HOST=0.0.0.0
      - NUXT_TELEMETRY_DISABLED=1
      - NUXT_PUBLIC_API_BASE=http://backend:8001/api/v1
    depends_on:
      - backend
    networks:
      - biblia-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 5
    labels:
      - "coolify.managed=true"

volumes:
  postgres_data:
    driver: local

networks:
  biblia-network:
    driver: bridge